# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "/jekyll-github-actions" # the subpath of your site, e.g. /blog
url: "https://ruabraun.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title: Blog 
email: rab014@gmail.com 
description: Blog on speech recognition and maybe other things # this means to ignore newlines until "baseurl:"
author:
    name: Rudolf Arseni Braun


remote_theme: zivong/jekyll-theme-hydure

navbar-links:
  Home: "index"
  Posts: "blog"
   

location: Montreux
skin: daylight

avatar: images/profpic.jpg


exerpt_length: 10

title-separator: "-"


markdown: kramdown
mathjax: true

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      ext-js: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" 
      show-avatar: false
  -
    scope:
      path: "" # all files
    values:
      layout: "page"

link-tags: false
